// GENERATED by scripts/index-screenshots.mjs — do not edit by hand.
// Add or remove files in public/proof/screenshots/ instead; the next build rewrites this.
import type { ProofShot } from "@/lib/landing";

export const PROOF_SCREENSHOT_FILES: ProofShot[] = [
];
