-- =============================================================================
-- 0027_id_form_fields.sql — the fields TIN and PhilHealth actually ask for.
--
-- Both services carried a four-field placeholder (full name, birthdate,
-- existing number, address) left over from the initial seed. The real intake
-- forms ask for far more, and none of it could be parsed from a pasted reply
-- because the fields did not exist to parse into.
--
-- Labels are the business's own, and the synonyms are the Taglish a customer
-- actually types — APILYEDO, BDAY, BPLACE, CP #, "Apilyedo sa Dalaga pa".
-- The delivery block (receiver, phone, purok, barangay, city, province) is not
-- here: it belongs to the customer, not the document, and is already parsed
-- into their record.
-- =============================================================================

update services
   set form_fields = '[{"key": "tin_number", "label": "TIN ID #", "type": "text", "required": false, "synonyms": ["tin id", "tin id number", "tin id no", "tin no", "tin number", "tin", "existing tin"]}, {"key": "last_name", "label": "Last Name (Apilyedo)", "type": "text", "required": true, "synonyms": ["apilyedo", "apelyido", "apellido", "surname", "last name", "family name"]}, {"key": "first_name", "label": "First Name", "type": "text", "required": true, "synonyms": ["firstname", "first name", "pangalan", "given name"]}, {"key": "middle_name", "label": "Middle Name", "type": "text", "required": false, "synonyms": ["middlename", "middle name", "gitnang pangalan"]}, {"key": "birthdate", "label": "Birthday", "type": "date", "required": true, "synonyms": ["birthday", "bday", "birthdate", "date of birth", "dob", "kapanganakan"]}, {"key": "civil_status", "label": "Civil Status", "type": "text", "required": true, "synonyms": ["civil status", "cvil status", "status", "estado", "estado sibil"]}, {"key": "sex", "label": "Gender", "type": "text", "required": true, "synonyms": ["gender", "sex", "kasarian"]}, {"key": "contact_number", "label": "Contact #", "type": "text", "required": true, "synonyms": ["contact", "contact no", "contact number", "cp", "cp no", "cp number", "cellphone", "mobile"]}, {"key": "address_line", "label": "Complete Address", "type": "text", "required": true, "synonyms": ["complete address", "address", "tirahan", "home address", "residence"]}, {"key": "zip", "label": "ZIP code", "type": "text", "required": false, "synonyms": ["zipcode", "zip code", "zip", "postal code"]}]'::jsonb
 where code = 'tin_id';

update services
   set form_fields = '[{"key": "philhealth_number", "label": "PhilHealth #", "type": "text", "required": false, "synonyms": ["philhealth", "philhealth no", "philhealth number", "philhealth id", "pin", "philhealth pin"]}, {"key": "last_name", "label": "Last Name (Apilyedo)", "type": "text", "required": true, "synonyms": ["apilyedo", "apelyido", "apellido", "surname", "last name", "family name"]}, {"key": "first_name", "label": "First Name (Pangalan)", "type": "text", "required": true, "synonyms": ["pangalan", "first name", "firstname", "given name"]}, {"key": "middle_name", "label": "Middle Name", "type": "text", "required": false, "synonyms": ["middlename", "middle name", "gitnang pangalan"]}, {"key": "birthdate", "label": "Birthday", "type": "date", "required": true, "synonyms": ["bday", "birthday", "birthdate", "date of birth", "dob", "kapanganakan"]}, {"key": "birth_place", "label": "Place of Birth", "type": "text", "required": true, "synonyms": ["bplace", "birthplace", "place of birth", "lugar ng kapanganakan"]}, {"key": "sex", "label": "Sex", "type": "text", "required": true, "synonyms": ["sex", "gender", "kasarian"]}, {"key": "civil_status", "label": "Civil Status", "type": "text", "required": true, "synonyms": ["status", "civil status", "estado", "estado sibil"]}, {"key": "contact_number", "label": "Mobile Number (CP #)", "type": "text", "required": true, "synonyms": ["cp", "cp no", "cp number", "contact", "contact no", "contact number", "cellphone", "mobile"]}, {"key": "house_number", "label": "House #", "type": "text", "required": false, "synonyms": ["house", "house no", "house number", "blk", "block", "lot"]}, {"key": "subdivision", "label": "Subdivision", "type": "text", "required": false, "synonyms": ["subdivision", "subd", "village", "purok", "street"]}, {"key": "barangay", "label": "Barangay", "type": "text", "required": true, "synonyms": ["barangay", "brgy", "bgy", "baranggay"]}, {"key": "municipality", "label": "City / Municipality", "type": "text", "required": true, "synonyms": ["municipality", "city", "bayan", "town", "lungsod"]}, {"key": "zip", "label": "ZIP code", "type": "text", "required": false, "synonyms": ["zipcode", "zip code", "zip", "postal code"]}, {"key": "mother_last", "label": "Mother \u2014 Maiden Last Name", "type": "text", "required": true, "synonyms": ["apilyedo sa dalaga pa", "apelyido sa dalaga pa", "maiden last name", "mothers maiden last name", "mother last name"]}, {"key": "mother_first", "label": "Mother \u2014 First Name", "type": "text", "required": true, "synonyms": ["pangalan ng ina", "mother first name", "mothers first name"]}, {"key": "mother_middle", "label": "Mother \u2014 Middle Name", "type": "text", "required": false, "synonyms": ["mother middle name", "mothers middle name"]}]'::jsonb
 where code = 'philhealth_id';
